### ISSUE TITLE
Torch-Neuron Error while tracing a custom CNN model

### ISSUE THREAD

**Issue by gohar-malik** [aws/aws-neuron-sdk#174]
Hi,

I am facing the following the error while compiling a custom build Pytorch CNN model, which only has `nn.Conv2d` layers in the `__init__()` function, and `nn.functional.avg_pool2d` and `nn.functional.relu` in the `forward()` function.  

`WARNING:Neuron:torch.neuron.trace failed on <torch_neuron.graph.Graph object at 0x7fc99daca8d0>; falling back to native python function call
WARNING:Neuron:torch.neuron.trace error: neuron-cc failed with the following command line call:
/home/ec2-user/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpxuo35hd0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpxuo35hd0/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 3, 512, 512], "float32"]}, "outputs": []}' -O2 --static-weights --num-neuroncores 4`

It used to work before the recent release of neuron sdk.
I am using the following instance for compilation:
AMI: Deep Learning AMI (Amazon Linux 2) Version 32.0
Instance type: inf1.2xlarge

**Comment by aws-diamant** [comment]
Hi @gohar-malik ,

are you intending to use NeuronCore Pipeline? (i'm asking based on "--static-weights --num-neuroncores 4")

could you share your code? i'll recreate the issue locally to provide with a better recommendation.

/Ron

**Comment by gohar-malik** [comment]
Hi @aws-diamant 

Yes i was intending to use NeuronCore Pipeline. I also tried compiling without these arguments and ended up with the same error.

You can find the code on this link:
https://github.com/gohar-malik/inferentia-art-remixer/blob/master/trace-vgg19.py

**Comment by aws-diamant** [comment]
Hey @gohar-malik ,

Thanks for sharing the code.
I was able to recreate the issue locally, and checking further with the team.

In the meantime, to make sure you are not blocked, I suggest the following workaround (which did compile successfully for me locally):
1. upgrade to latest neuron-cc (version 1.0.20600.0+0.b426b885f), and remove 'static-weights' flag (i.e. use data-parallel mode)
3. use only 'relu4_1' as output from the model (rather than a list of outputs), as the SDK currently doesn't support returning lists

I'll keep you posted as we root-cause and fix the issue.

/Ron

**Comment by gohar-malik** [comment]
Hi @aws-diamant 
Thank you very much for your suggestions. I'll try these workarounds. Hopefully it will work like that. 
But I really need to return output from multiple layers. Is there any other way to do that with neuron?

**Comment by aws-diamant** [comment]
Hey @gohar-malik,
Yes, we can just return multiple outputs instead of a list of outputs.

i.e. just replace:
        return [relu1_1, relu2_1, relu3_1, relu4_1, relu3_2, conv4_1]
with:
        return relu1_1, relu2_1, relu3_1, relu4_1, relu3_2, conv4_1

**Comment by gohar-malik** [comment]
@aws-diamant 

Oh okay. Got it. 

Thanks again Ron.

**Comment by aws-diamant** [comment]
gladly @gohar-malik 

and just one more note:
since the output is so large, you might encounter a challenge in allocating hugepages for ofmaps (I noticed that on a in1.2xl).

If you do, this is solvable by following the guidelines here:
https://github.com/aws/aws-neuron-sdk/blob/fc68a5f416c303f0a44198ece8b5c73f1731c6bb/docs/neuron-runtime/nrt_start.md#step-3-configure-nr_hugepages

/Ron

**Comment by aws-taylor** [comment]
Hi @gohar-malik,

 I'm closing this ticket for now. Feel free to re-open if you have further questions.

Regards,
Taylor
