### ISSUE TITLE
--fast-math option for improved accuracy/performance trade-off

### ISSUE THREAD

**Issue by aws-maens** [aws/aws-neuron-sdk#333]
--fast-math option for improved accuracy/performance trade-off

**Comment by aws-donkrets** [comment]
Suggest we change this item to describe the capability we are giving to our customers instead of how we are implementing it. Specifically, we are giving customer the ability to select between precision and inference performance.
Higher precision results take more time (slower inference perf) while less precision can result in faster inference performance.

**Comment by aws-maens** [comment]
Part of Neuron 1.16.0 release
