### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by kutysam** [aws/aws-neuron-sdk#366]
Are there any plans to support python 3.9?

There are some cases where the models are built with python 3.9 which results it in not being able to run well in neuron.
I do understand that neuron's code is closed source so I guess only the AWS team is able to answer if there are any plans to support 3.9.

For reference:
- Python 3.8 experimental support was added on Neuron v1.13.0 (May 1st 2021) ==> https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuronrelease/previous-content.html#neuron-v1-13-0-may-1st-2021

**Comment by aws-joshim** [comment]
@kutysam Neuron SDK does not support python 3.9 because of compatibility issues with certain versions of frameworks, specifically, Tensorflow 1.15.x requires older versions of python (3.7 or older). We are working towards enabling python 3.9 support with Neuron 2022 roadmap. Can you provide pointers to use cases /models that require python 3.9  support so that we can look into potential options to workaround the python 3.9 dependency?

**Comment by kutysam** [comment]
Noted on that. I will close this ticket for now.
