### ISSUE TITLE
Generative model (MarianMT, BART) performance is poor

### ISSUE THREAD

**Issue by phaterpekar** [aws/aws-neuron-sdk#368]
The tutorial provided here for generative models seems outdated:
 https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html

**1. **How do these run with the Data Parallel Inference API ? Seems like these don't seem to be supported on torch-neuron >= 1.8.* which is required for parallelization?**** 

**2. **Also the models don't compile anymore on 1.8.*, the trace step fails for the supplied notebook.**** 
model_neuron.trace(
    model=model_cpu,
    num_texts=num_texts,
    num_beams=num_beams,
    max_encoder_length=max_encoder_length,
    max_decoder_length=max_decoder_length,
)
**Error: TypeError: forward() got an unexpected keyword argument 'encoder_padding_mask'**

3**.** On torch-neuron==1.7.*,  without the parallelization support, only one neuron core is being utilized at best. Also the performance is quite poor(similar to CPU) on max_encoder_ length/max_decoder_lengths of 128 or 256 
& more which is required for translating longer sentences, without losing context.

**Comment by aws-joshim** [comment]
@phaterpekar For question 1 and 3, DataParallel Inference APIs only works with torch.jit.ScriptModules. The transformers  generator-like models cannot be expressed in a single torch.jit.ScriptModule due  to dynamic control flow. In order to get parallelism on 1.7, you would need to load multiple  models across cores. It is expected that the performance would degrade with longer sequence  lengths. 

For question 2, please note that Neuron Marian MT model is currently supported with specific versions  of torch and transformers i.e torch==1.7 and transformers==4.0.1 for the following reasons – Our tutorial references internal transformers APIs (for example the encoder/decoder keyword arguments). Newer versions of transformers have changed or removed these arguments which means updating the version will cause errors due to missing/invalid argument names. The missing symbol Error: TypeError: forward() got an unexpected keyword argument 'encoder_padding_mask' is due to a later version of transformers which is currently not supported for this model on Neuron. We will look into extending support for Marian with later versions of torch and transformers in the future.

**Comment by phaterpekar** [comment]
@aws-joshim  Thank you for the response!  Would greatly appreciate extending that support in the future.

For now, with generator-like models, would using the NEURONCORE_GROUP_SIZES, by setting the **_os.environ_**  be the best approach to load models across all the cores on inf1.6xlarge.  (Although seems like this will be deprecated in the future)

At the moment I am creating multiple instances of the model and using threading to utilize all the cores,  is there a better approach to ensure full utilization of all the 16 cores on 6xlarge?

If you could point to the appropriate documentation, that works for generative models, that would be great!

**Comment by mrnikwaws** [comment]
Hi Ankit,

We're aware that generative models don't currently perform well on neuron, and we have created a roadmap issue to track upcoming effort in respect of improving performance: https://github.com/aws/aws-neuron-sdk/issues/370

The documentation for the replacement environment variables is here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-configurable-parameters.html

For now the link you've already seen is the best available.  I'm going to close this issue for now since, we don't have a better answer for accelerating generator models and that is only performant for short sequence lengths.
