### ISSUE TITLE
More tensor to device

### ISSUE THREAD

**Issue by manhtd98** [aws/aws-neuron-sdk#446]
I want to move tensor to device
```
torch.from_numpy(scale_factor).to("cuda:0")
```
How can i do move it to neuron core?

**Comment by jluntamazon** [comment]
Currently there is no way to manually move a tensor to the device. Data will be moved for you automatically for any compiled model.

The technical justification why this was not supported is because after compilation, `torch-neuron` executes the entire model graph as a *single fused operator*. This is dissimilar to typical CUDA/CPU operator dispatch where the operator device is chosen according to the input tensor device. On Neuron, this means that CPU tensor data is automatically transferred to the device as soon as the fused operator is executed. The results are transferred back only when the full subgraph has been executed on the device. 

This provides convenience from an execution perspective since inference on CPU/Neuron should look no different from each other. However, this sacrifices fine-grained control of when data is moved to/from the device. Note that while explicit tensor movement is not currently possible, we may add support for it in the future to enable *specific* use-cases.

**Comment by manhtd98** [comment]
did you get error with neuroncc. I can not run the sample tutoriol ?

**Comment by jluntamazon** [comment]
Hi @manhtd98,
If you ran into a error during installation or compilation, please let us know the specific error and steps taken to produce the error.

**Comment by manhtd98** [comment]
RuntimeError: Please check that neuron-cc is installed and working properly. You can install neuron-cc using 'python3 -m pip install neuron-cc[tensorflow] -U --extra-index-url=https://pip.repos.neuron.amazonaws.com'
I got this error

**Comment by jluntamazon** [comment]
In order to be able to compile models for pytorch, `neuron-cc` must be installed. The error you got indicates that the local python environment cannot find the `neuron-cc` package. This is most likely because the package is not installed correctly, but may also be occurring due to other environment issues.

Start by validating that you have installed `neuron-cc` using the command recommended by the error message:
```
python3 -m pip install neuron-cc[tensorflow] -U --extra-index-url=https://pip.repos.neuron.amazonaws.com/
```
For more detailed setup information please reference the main installation guide: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html

You should then be able to validate that `neuron-cc` is installed by executing:
```
neuron-cc --version
```
This will display the version information.

Another option is to check your pip environment to confirm that it is installed:
```
pip list
```
Under your dependencies, you should see `neuron-cc`.

Once you have validated that `neuron-cc` is installed, please try rerunning your script.

**Comment by aws-joshim** [comment]
@manhtd98 checking in on whether you are successfully able to compile your model with torch-neuron after installing neuron-cc. Please let us know if you run into any other issues that we can help with

**Comment by manhtd98** [comment]
i have some error and i cannot fix it. so i switch again to GPU
