### ISSUE TITLE
ONNX neuron compiler

### ISSUE THREAD

**Issue by hannan72** [aws/aws-neuron-sdk#465]
Currently, I am running an ONNX model on inferentia. During the deployment, I got this warning:
```
Your model is not compiled. Please compile your model before using Inferentia.
```
On the other hand, inference time of ONNX model is 3x higher than the PyTorch model. Is it normal?
Is there any way to compile the onnx model with neuron?

**Comment by aws-stdun** [comment]
Hi [hannan72](https://github.com/hannan72),

When you say you are “running an ONNX model on inferentia”, do you mean you are using CPU?
In order to use the Inferentia hardware, you would have to convert your ONNX model to PT and compile using the [trace API](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/api-compilation-python-api.html).

**Comment by hannan72** [comment]
Hi @aws-stdun 
Thanks a lot for your reply.
Yes, I am running on cpu.

**Comment by aws-stdun** [comment]
Okay, please compile your model first using the mentioned trace API and feel free to file a new ticket if you run into other issues.
