### ISSUE TITLE
torch-neuron latest version is not getting installed in arm based machine. 

### ISSUE THREAD

**Issue by dingusagar** [aws/aws-neuron-sdk#466]
The version that is getting installed on x86_64 architecture machine is `torch-neuron==1.11.0.2.3.0.0` .
whereas the version that is getting installed on arm architecture is `torch-neuron==1.0`.

Just wanted to check if this is expected. Is the latest version compatible with arm is much older compared to x86_64 ?

**Comment by aws-stdun** [comment]
Hi [hannan72](https://github.com/hannan72),

When you say you are “running an ONNX model on inferentia”, do you mean you are using CPU?
In order to use the Inferentia hardware, you would have to convert your ONNX model to PT and compile using the [trace API](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/api-compilation-python-api.html).

**Comment by awsrjh** [comment]
Hi dingusagar

We currently do not support an ARM version of Neuron, so the default (1.0) in PIP is being installed. We will try to rectify the dependencies to prevent installation on arm systems. Thanks for letting us know.
