### ISSUE TITLE
Pipeline parallel inference

### ISSUE THREAD

**Issue by DevBey** [aws/aws-neuron-sdk#467]
Hi, I have converted and deployed a BERT based model on saemaker, but it's constantly throwing no workers available error probably because of too many concurrent requests. while going through the documents what I found was pipeline parallel mode would enhance the performance by loading the model in every core so that every worker can directly serve requests instead of a single model.

the process I followed is 
1. while conversion using torch neuron provide the --neuroncore-pipeline-cores parameter during compliation.
2. deploy the model on sagemaker normally 
             - using the sagemaker-python-sdk PytorchModel class.
             - providing the correct inference.py within the class.
             - providing the latest container image from the sagemaker DLC repo.
             -  that's how I normally deploy inferentia models without pipeline parallel configuration.

Questions
1. Am I doing it correctly ?? is there any other settings I Need to do ?? 
2. How do I confirm that the model is now deployed in the pipeline parallel mode ?? 
4. let's say now I want to deploy the model on a bigger instance say inf1.2xlarge do I need to again compile the model with appropirate cores ??

**Comment by aws-taylor** [comment]
Hello @DevBey,

  `--neuroncore-pipeline-cores` works by splitting a large model into a pipelined series of smaller models, allowing for improved performance. See https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/technotes/neuroncore-pipeline.html for more details.
  
 _"I found was pipeline parallel mode would enhance the performance by loading the model in every core so that every worker can directly serve requests instead of a single model."_ 

 Unfortunately this is not quite correct. Suppose `--neuroncore-pipeline-cores=4`, then the first ~1/4th of your model will be placed on core 1, the second ~1/4th on core 2, and so on. This will allow for multiple in-flight requests, however it will not enable each core to serve requests directly - only the first core can receive the initial request.
 
 Questions:
 
 _"Am I doing it correctly ?? is there any other settings I Need to do ??"_ 
 
 See above.
 
 _"How do I confirm that the model is now deployed in the pipeline parallel mode ??"_
 
 You can use `neuron-top` to see loaded models - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-tools/neuron-top-user-guide.html
 
 _"Let's say now I want to deploy the model on a bigger instance say inf1.2xlarge do I need to again compile the model with appropirate cores ??"_
 
 If you compile with `--neuroncore-pipeline-cores=N`, then you will need to use an instance with at least  `N` neuron cores. There are 4 neuron cores per Inferentia chip. Please see the table below for details.

Instance size | vCPUs | Memory (GiB) | Instance Storage | Inferentia chips | Inferentia chip-to-chip interconnect | Network Bandwidth (Gbps)*** | EBS Bandwidth
-- | -- | -- | -- | -- | -- | -- | --
inf1.xlarge | 4 | 8 | EBS only | 1 | N/A | Up to 25 | Up to 4.75
inf1.2xlarge | 8 | 16 | EBS only | 1 | N/A | Up to 25 | Up to 4.75
inf1.6xlarge | 24 | 48 | EBS only | 4 | Yes | 25 | 4.75
inf1.24xlarge | 96 | 192 | EBS only | 16 | Yes | 100 | 19

(https://aws.amazon.com/ec2/instance-types/)

**Comment by DevBey** [comment]
Hi @aws-taylor,

Thanks for the response. I read the article and it seems pipeline parallel mode is only for huge model, would DistillBert like model benefit from this?? 
btw the reason for my confusion was this article `https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/pipeline_tutorial/neuroncore_pipeline_pytorch.html` which shows how for real-time inference with batch size one would be way faster on pipeline model 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/85338857/186060151-03b95648-13c0-4c51-8ca1-2c62138e4cbb.png">

Can you please what's the best way to scale according to my scenario

`We have deployed https://www.sbert.net/ on inferentia, where we have hundreds of requests with batch size one being made in parallel at the same time, for now the only way to scale is to increase the number of instances. Would suggest this is the best way to go or can we optimize the deployment for this scenario by compiling models in a separate way like data parallel or pipeline parallel`

correct me if I am wrong data parallel won't quite be any beneficial as the request is not in batch, which leaves us with just pipeline parallel mode, would that be beneficial or is there anything else you would suggest??

**Comment by awsrjh** [comment]
Hi DevBey

The biggest benefit of the pipeline parallel mode that the  --neuroncore-pipeline-cores=N mode provides is the abiltity to spread the model over more NeuronCores, which in turn means more on-chip ram is available for the model, which in turn means possibly lower latency. I say possibly as there is also some overhead of the "daisy chain" between Neuron Cores, so there may be cases where the use of additional cores may not help as much, or possibly will not be as linearly helpful. Given that it helps with some cases to reduce the latency of execution, it is typically useful in combination with  a small (ie ==1 ) batch size. 

Your question above asks : "correct me if I am wrong data parallel won't quite be any beneficial as the request is not in batch"  - the issue here would be that the batch mode is typically best for throuput-oriented applciations (like bulk execution) as the  individual inferences are combined into single transactions in the chip, which helps throughput.

You may find the best combination for your application is to use multiple NeuronCores, each loaded with a copy of your model in batch=1. 

This document may help you for this: 

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/perf/torch-neuron-dataparallel-app-note.html?highlight=data%20parallel

This may also be helpful:

https://huggingface.co/blog/bert-inferentia-sagemaker
